name: Build & Publish (Windows)

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20 and enable npm cache
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "package-lock.json"

      - name: Install deps
        run: npm ci

      - name: Build app (tsc/webpack)
        run: npm run build

      - name: Package & publish to GitHub Releases
        run: npx electron-builder --win nsis -p always
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: build/**
